In [2]:
!pip3 install numpy


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 1.1 MB/s eta 0:00:0000:0100:010m

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: pip3 install --upgrade pip


In [7]:
import numpy as np

In [4]:
print (np.__version__)

2.4.0


In [5]:
## 1. creating arrays

In [7]:
list1 = [18 , 45 , 10 , 1 , 7 ,33 ]
print(list1)

[18, 45, 10, 1, 7, 33]


In [10]:
arr_list1 = np.array(list1)      # list to array
print(arr_list1)

[18 45 10  1  7 33]


In [8]:
list1 = [18 , 5 , 95 ,33 ]
list2 = [10 , 7 , 99 , 17 ]
arr_list1_2 = np.array([list1 , list2])    # 2d array
print(arr_list1_2)
print(type(arr_list1_2))

[[18  5 95 33]
 [10  7 99 17]]
<class 'numpy.ndarray'>


In [26]:
print(arr_list1_2.ndim)       # printing dimention of array output is 2 mens 2d array

2


In [11]:
print(type(arr_list1))

<class 'numpy.ndarray'>


In [33]:
list1 = [18 , 45 , 95 ,33 ]
list2 = [10 , 7 , 99 , 17 ]
list3 = [9 , 11 , 99 , 69 ]
arr_list1_3 = np.array([[list1 , list2 , list3]])  # 3d array
print(arr_list1_3)

[[[18 45 95 33]
  [10  7 99 17]
  [ 9 11 99 69]]]


In [34]:
print(arr_list1_3.ndim)         # printing dimention of array output is 3 mens 3d array

3
