In [14]:
!pip3 install numpy


[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: pip3 install --upgrade pip


In [15]:
import numpy as np


In [16]:
arr1 = np.array([[1,2,3,4] , [5,6,7,8]])
print(arr1)
print("shape : " , arr1.shape)     # 2 Shape = (rows, columns) = (2, 4)
print("size : " , arr1.size)       # total element in array 
print("dtype : " , arr1.dtype)     # print data type "int 64"
print("n_dim : " , arr1.ndim)      # dimention of array 

[[1 2 3 4]
 [5 6 7 8]]
shape :  (2, 4)
size :  8
dtype :  int64
n_dim :  2


In [17]:
arr3 = np.array([[[18 , 4.5 , "aakash"] , [10 , 7.0 , "ansh"]]])
print(arr3)
print("shape : " , arr3.shape)   # 1 block, 2 rows, 3 columns  
print("size : " , arr3.size)       
print("dtype : " , arr3.dtype)     # Mixed data types
print("n_dim : " , arr3.ndim)    

[[['18' '4.5' 'aakash']
  ['10' '7.0' 'ansh']]]
shape :  (1, 2, 3)
size :  6
dtype :  <U32
n_dim :  3


In [ ]:
''' 
When a NumPy array contains mixed data types, NumPy converts all elements to a 
common data type, usually object or string.

1. Array contains int + float + string
2. NumPy chooses string (Unicode) or object type
3. Numbers are converted to strings

'''

In [13]:
# 3. Array initialization methods

In [ ]:
zero_arry_arry = np.zeros((2,4))      # printig zero(0) array 2 row 4 columns
print(zero_arry_arry)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# one array

one_arry = np.ones((2,4))      # printig one(1) array 2 row 4 columns
print(one_arry)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# full array 
full_arr = np.full((3,5) , 18)  # printing full array 3 row 5 columns using 18 number 
print(full_arr)

[[18 18 18 18 18]
 [18 18 18 18 18]
 [18 18 18 18 18]]


In [ ]:
# Identity Matrix :

# An identity matrix is a square matrix with 1 on the main diagonal and 0 elsewhere.

id_arr = np.eye(3)
print(id_arr)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# empty array :

#np.empty() creates an array with uninitialized (random) values.

print(np.empty(2))

[2.33419537e-312 2.20687562e-312]


In [ ]:
# evenly spaced array
print(np.arange(1,10,2))  # np.arange(start, stop, step)

# np.arange(1, 10, 2) prints numbers from 1 to 9 with a gap of 2, like [1 3 5 7 9].


[1 3 5 7 9]


In [ ]:
# np.linspace(5, 50, 10) prints 10 equally spaced values between 5 and 50,
#  like [ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.] 

print(np.linspace(5,50,10)) # np.linspace(start, stop, number_of_values)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [ ]:
# random values array - float data typr

random_arr = np.random.rand(3,5)
print(random_arr)

# np.random.rand(3,5) creates a 3 × 5 array with random decimal values between 0 and 1.

[[0.3867834  0.49958719 0.18704503 0.43693104 0.58502514]
 [0.48185852 0.16201524 0.76486331 0.60832041 0.4566515 ]
 [0.59721903 0.12586225 0.32820239 0.4008243  0.16218879]]


In [46]:
# random values array - int data typr

random_arr = np.random.randint(1, 100, (4, 4))
print(random_arr)

# np.random.randint(1, 100, (4, 4)) creates a 4 × 4 array of random integers 
# between 1 and 99.


[[61 53  1 44]
 [29 70 14  3]
 [17 92 87 12]
 [42 40 71 33]]
