In [5]:
!pip3 install numpy



[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: pip3 install --upgrade pip


In [4]:
import numpy as np

In [80]:
a = np.array([2,4,6,8,10]) 
print(a)
print(a[3]) # printig the number using indexing [0,1,2,3,4]
print(a[-5])  # nagative indexing [-5,-4,-3,-2,-1] output is [8]

# slicing :
# stop - index, that is not included in output

print(a[1:3])  # array[start:stop] output is [4,6]
print(a[0:4:2]) # array[start:stop:step] output is [2,6]


[ 2  4  6  8 10]
8
2
[4 6]
[2 6]


In [ ]:
arr2 = np.array([[1,2,3,4] , [5,6,7,8]])
print(arr2)
# 2 → number of rows
# 4 → number of columns
# print(arr2[row, :column])


[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(arr2[:]) #  print full array

print("2st columns :" , arr2[: , 1]) # print index 1 columns 
print("2st Row :" , arr2[1,:])   # print index 1 row  

print(arr2[0,2])   # Row 0, column 2
#.  both give the same result
print(arr2[0][2])  # row 1 , column 3


[[1 2 3 4]
 [5 6 7 8]]
2st columns : [2 6]
2st Row : [5 6 7 8]
3
3
[[1 2 3 4]
 [5 6 7 8]]


In [78]:
print(arr2[0:2 , 1:3]) # The end index is not counted. Only the start index is included.

# arr2[start_row : end_row, start_col : end_col]
# start_row:end_row = 0:2 → rows 0 and 1
# start_col:end_col = 1:3 → columns 1 and 2
# Row 0, columns 1-2: output is [2,3]
# Row 1, columns 1-2: output is [6,7]
print(arr2[0:2 , 0:3])

[[2 3]
 [6 7]]
[[1 2 3]
 [5 6 7]]


In [ ]:
arr3 = np.array([[1,2,3] , [4,5,6] , [7,8,9]])  # 2d array
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [110]:
print(arr3[ 2,: ]) # printig row number 3 using index 2
print(arr3[ :, 2]) # printig column number 3 using index 2
print(arr3[1:3 , 1:3]) 
print(arr3[1 , 1])
print(arr3[2][0])


[7 8 9]
[3 6 9]
[[5 6]
 [8 9]]
5
7


In [ ]:
print(arr3[:,0]) # print 1 column
print(arr3[::2,2]) # tskip 1 element in 3 column
print(arr3[::,1:2]) # :: → take all rows .  All rows, column 1 (slice)

[1 4 7]
[3 9]
[[2]
 [5]
 [8]]


In [16]:
#5 Array Reshaping and Flattening
arr1 = np.array([1,2,3,4,5,6])
print(arr1)

[1 2 3 4 5 6]


In [ ]:
reshape = arr1.reshape((6,1)) # 5 row and 1 columns
print(reshape)

reshape2 = arr1.reshape((2,3)) # 2 row and 3 columns
print(reshape2)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
print(reshape2.flatten()) # back array in normal forme

[1 2 3 4 5 6]


In [ ]:
#. Array Stacking 
a = np.array([1,3,5,7,9])
b = np.array([2,4,6,8,10])

print(np.vstack((a,b))) # vertical stacking - row wise 2D--array
print(np.hstack((a,b))) # horizontal stacking - column wise 1D--array

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]
[ 1  3  5  7  9  2  4  6  8 10]


In [ ]:
#. Array Splitting
c = np.array([[1,3,5,7] ,[2,4,6,8]] )
print(c)

[[1 3 5 7]
 [2 4 6 8]]


In [44]:
Hsplit = np.hsplit(c,4) # split the array in horizontal in 4 grops 
for s in Hsplit:
    print(s)


[[1]
 [2]]
[[3]
 [4]]
[[5]
 [6]]
[[7]
 [8]]


In [ ]:
Vsplit = np.vsplit(c,2) # split the array in vertical in 2 grops 
for v in Vsplit:
    print(v)

[[1 3 5 7]]
[[2 4 6 8]]


In [ ]:
#. Mathematical Operations on Array

In [ ]:
x = np.array([10, 20, 30])

print(x)
print(x + 10) # add
print(x - 20) # subs
print(x * 2) # multiply
print(x / 10) # divide


[10 20 30]
[20 30 40]
[-10   0  10]
[20 40 60]
[1. 2. 3.]


In [ ]:
y = np.array([1,4,16,25])

print(y)
print(np.square(y)) #  finding square
print(np.sqrt(y))  # finding root 


[ 1  4 16 25]
[  1  16 256 625]
[1. 2. 4. 5.]


In [ ]:
# Q.1 
#  array of angles in degrees
angles = np.array([0, 30, 45, 60, 90])
print(angles)

# convert degrees into radians
rad = np.radians(angles)
print(rad)

# find sine value of each angle (in radians)
print(np.sin(rad))


[ 0 30 45 60 90]
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
[0.         0.5        0.70710678 0.8660254  1.        ]


In [ ]:
#  Q.2 
#       np.pi = π

# angles given in radians using np.pi
z = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])

# print the array
print(z)

# calculate cosine of each element
print(np.cos(z))



[0.         0.52359878 0.78539816 1.04719755 1.57079633]
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [ ]:
#. Mathematical Operations on Muliple Arrays

In [ ]:
a = np.array([10,20,30,40,50])
b = np.array([60,70,80,90,100])

print(a)
print(b)

[10 20 30 40 50]
[ 60  70  80  90 100]


In [83]:
print(np.add(a,b)) # a + b
print(np.subtract(a,b)) # a - b
print(np.multiply(a,b)) # a * b
print(np.divide(b,a)) # b / a

[ 70  90 110 130 150]
[-50 -50 -50 -50 -50]
[ 600 1400 2400 3600 5000]
[6.         3.5        2.66666667 2.25       2.        ]


In [87]:
print(np.dot(a,b)) # a*b then add  [ 600 + 1400 + 2400 + 3600 + 5000] = [13000] called dot product

13000


In [ ]:
t = np.array([[1,2,3,4], [5,6,7,8]])
print(t)

print(t.T) #  .T is used to transpose an array by converting rows into columns. use only in 2D and 3D array 

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [ ]:
# Statistical Functions

In [91]:
a = np.array([[1,2,3,4], [5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(np.sum(a))

print(np.mean(a)) # (1+2+3+4+5+6+7+8) / 8 = 36 / 8 = 4.5

print(np.median(a)) # (4 + 5) / 2 = 4.5

print(np.std(a)) # Standard Deviation

print(np.min(a)) # finds the smallest value in the array

print(np.max(a)) # finds the largest value in the array




36
4.5
4.5
2.29128784747792
1
8


In [ ]:
#. Array Comparison

In [106]:
a = np.array([10,20,30,40,50])
b = np.array([60,20,80,90,100])

print(a)
print(b)

[10 20 30 40 50]
[ 60  20  80  90 100]


In [ ]:
# comparing each elements

print(a == b)
print(a != b)
print(a >= b)
print(a <= b)


[False  True False False False]
[ True False  True  True  True]
[False  True False False False]
[ True  True  True  True  True]


In [ ]:
# comparing complete array

print(np.array_equal(a,b))


False
False


In [ ]:
#. Broadcasting

In [ ]:
# 1-D array
c = np.array([2,4,6,8])
d = np.array([3])
print(c)
print(d)

[2 4 6 8]
[3]


In [ ]:
print(c + d)  # add
print(c - d) # subs
print(c * d) # multiply
print(c / d) # divide


[ 5  7  9 11]
[-1  1  3  5]
[ 6 12 18 24]
[0.66666667 1.33333333 2.         2.66666667]


In [ ]:
# 2-D array
x = np.array([[10,20,30] , [40,50,60]]) # 2-D array
y = np.array([1,2,3]) # 1-d array

print(x)
print(y)

[[10 20 30]
 [40 50 60]]
[1 2 3]


In [ ]:
print(x + y) # add
print(x * y) # multiply

[[11 22 33]
 [41 52 63]]
[[ 10  40  90]
 [ 40 100 180]]


In [ ]:
#. Hanndling with nan & inf

In [122]:
data1 = np.array([2 , 3 , np.nan , 4 , 5 , np.inf])
print(data1)

[ 2.  3. nan  4.  5. inf]


In [ ]:
print(np.isnan(data1)) # printing nan value
print(np.nan_to_num(data1))  # replace nan with 0 (or specified number) in the array

print(np.isinf(data1)) # printing inf (infinite) value 
print(np.isfinite(data1)) # printing finite value 

[False False  True False False False]
[2.00000000e+000 3.00000000e+000 0.00000000e+000 4.00000000e+000
 5.00000000e+000 1.79769313e+308]
[False False False False False  True]
[ True  True False  True  True False]


In [ ]:
# save and Load arrays

In [131]:
arr = np.array([70,16,477,220])

print(arr)                    # print the array

np.save('my_array.npy', arr)   # save array to a file named 'my_array.npy'


[ 70  16 477 220]


In [132]:
loadd_arr = np.load('my_array.npy')   # load the array from the file 'my_array.npy'

print(loadd_arr)                       # print the loaded array


[ 70  16 477 220]


In [ ]:
#Q.3 Create 5X5 matrix with values from 1 to 25 
# > extract last row, first column, mub matrix containing 3X3

In [138]:
# create 5x5 matrix with values 1 to 25
matrix = np.arange(1, 26).reshape(5, 5)
print("5x5 Matrix:\n", matrix)

# extract last row
last_row = matrix[-1, :]          # -1 means last row
print("Last row:", last_row)

# extract first column
first_column = matrix[:, 0]       # all rows, column 0
print("First column:", first_column)

# extract 3x3 submatrix (middle 3x3)
sub_matrix = matrix[1:4, 1:4]     # rows 1-3, columns 1-3
print("3x3 Submatrix:\n", sub_matrix)


5x5 Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Last row: [21 22 23 24 25]
First column: [ 1  6 11 16 21]
3x3 Submatrix:
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [ ]:
# Q.4  Broadcasting: multiply shape- (4,1) matrix with shape- (4,)

In [ ]:
a = np.array([[2],
             [3],
             [4],
             [5]]) # (4,1) shape
 
b = np.array([20,30,40,50]) # (4,) shape

print(a)
print(b)

print(np.shape(a))
print(np.shape(b))


[[2]
 [3]
 [4]
 [5]]
[20 30 40 50]
(4, 1)
(4,)


In [ ]:
print(a + b) # adds a and b element-wise using broadcasting

print(a * b) # multiplies a and b element-wise using broadcasting

[[22 32 42 52]
 [23 33 43 53]
 [24 34 44 54]
 [25 35 45 55]]
[[ 40  60  80 100]
 [ 60  90 120 150]
 [ 80 120 160 200]
 [100 150 200 250]]
