In [1]:
!pip3 install numpy


[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: pip3 install --upgrade pip


In [2]:
import numpy as np

In [ ]:
'''
Q.1 
Create a 1D NumPy array with values:
Print the array and its type.
'''

In [ ]:
arr = np.array([5, 10, 15, 20, 25])
print(arr)
print(type(arr))

[ 5 10 15 20 25]
<class 'numpy.ndarray'>


In [ ]:
# Q.2 Create a 2 × 3 NumPy array and print:
#  shape , size , Number of dimensions

In [16]:
a = np.arange(1 ,7).reshape(2,3)
print(a)
print("shape :" , np.shape(a))
print("size :" , np.size(a))
print("Dimensions: " ,  np.ndim(a))


[[1 2 3]
 [4 5 6]]
shape : (2, 3)
size : 6
Dimensions:  2


In [ ]:
# Q.3 create : A 3 × 3 zero matrix , A 2 × 4 ones matrix

In [22]:
zero_arr = np.zeros((3,3))
print(zero_arr)

one_arr = np.ones((2 , 4), dtype= int)
print(one_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1 1]
 [1 1 1 1]]


In [ ]:
# Q.4 Create a NumPy array with numbers 1 to 20 and 
# reshape it into a 4 × 5 matrix.

In [24]:
arr1 = np.arange(1,21).reshape(4,5)
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [40]:
# Q.5 print 50 , first row and last column

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print(arr)
print(arr[1,1]) # print 50
print(arr[0,:]) # first row
print(arr[ : ,2]) # last column
print(arr[0:2 , 1:3])


[[10 20 30]
 [40 50 60]
 [70 80 90]]
50
[10 20 30]
[30 60 90]
[[20 30]
 [50 60]]


In [41]:
# Q.6 Mathematical Operations perform a+b , a-b and a*b .

a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print(a)
print(b)

print(a + b)
print(a - b)
print(a * b)

[2 4 6]
[1 3 5]
[ 3  7 11]
[1 1 1]
[ 2 12 30]


In [ ]:
# Q.7 using Statistical Functions print Maximum marks  , Minimum marks , 
#  Sum of all marks and Average marks

In [44]:
marks = np.array([65, 70, 80, 90, 85])
print(marks)
print(np.max(marks))       # Maximum marks
print(np.min(marks))       # Minimum marks
print(np.sum(marks))       # Sum of marks
print(np.average(marks))   # Average marks


[65 70 80 90 85]
90
65
390
78.0


In [ ]:
# Q.8 using Broadcasting Multiply every element by 5 using NumPy.

In [46]:
a  = np.array([[1, 2, 3],
                [4, 5, 6]])
b = np.array([5])

print(a)
print(b)
print(a * b)

[[1 2 3]
 [4 5 6]]
[5]
[[ 5 10 15]
 [20 25 30]]


In [52]:
# Q.9 5×5 matrix with last row, first column, middle 3×3 ?

x = np.arange(1,26).reshape(5,5)
print(x)

# Last row
print(x[4,:])

# First column
print(x[:,0])

# Middle 3x3 matrix (top-left 3x3)
print(x[0:3, 0:3])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[21 22 23 24 25]
[ 1  6 11 16 21]
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
